/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct range_in {
	long min;
	long max;
};
typedef struct range_in range_in;

struct sum_out {
	long result;
};
typedef struct sum_out sum_out;

#define SUM_PROG 0x31110000
#define SUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM_PROC 1
extern  sum_out * sum_proc_1(range_in *, CLIENT *);
extern  sum_out * sum_proc_1_svc(range_in *, struct svc_req *);
extern int sum_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM_PROC 1
extern  sum_out * sum_proc_1();
extern  sum_out * sum_proc_1_svc();
extern int sum_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_range_in (XDR *, range_in*);
extern  bool_t xdr_sum_out (XDR *, sum_out*);

#else /* K&R C */
extern bool_t xdr_range_in ();
extern bool_t xdr_sum_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
