/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ssnfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

create_output *
create_file_1(argp, clnt)
	create_input *argp;
	CLIENT *clnt;
{
	static create_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, create_file, xdr_create_input, argp, xdr_create_output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

list_output *
list_files_1(argp, clnt)
	list_input *argp;
	CLIENT *clnt;
{
	static list_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, list_files, xdr_list_input, argp, xdr_list_output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

delete_output *
delete_file_1(argp, clnt)
	delete_input *argp;
	CLIENT *clnt;
{
	static delete_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, delete_file, xdr_delete_input, argp, xdr_delete_output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

write_output *
write_file_1(argp, clnt)
	write_input *argp;
	CLIENT *clnt;
{
	static write_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, write_file, xdr_write_input, argp, xdr_write_output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

read_output *
read_file_1(argp, clnt)
	read_input *argp;
	CLIENT *clnt;
{
	static read_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, read_file, xdr_read_input, argp, xdr_read_output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

copy_output *
copy_file_1(argp, clnt)
	copy_input *argp;
	CLIENT *clnt;
{
	static copy_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, copy_file, xdr_copy_input, argp, xdr_copy_output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
