/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SSNFS_H_RPCGEN
#define _SSNFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct open_input {
	char user_name[10];
	char file_name[10];
};
typedef struct open_input open_input;

struct open_output {
	int fd;
};
typedef struct open_output open_output;

struct read_input {
	char user_name[10];
	int fd;
	int numbytes;
};
typedef struct read_input read_input;

struct read_output {
	struct {
		u_int out_msg_len;
		char *out_msg_val;
	} out_msg;
};
typedef struct read_output read_output;

struct write_input {
	char user_name[10];
	int fd;
	int numbytes;
	struct {
		u_int buffer_len;
		char *buffer_val;
	} buffer;
};
typedef struct write_input write_input;

struct write_output {
	struct {
		u_int out_msg_len;
		char *out_msg_val;
	} out_msg;
};
typedef struct write_output write_output;

struct list_input {
	char user_name[10];
};
typedef struct list_input list_input;

struct list_output {
	struct {
		u_int out_msg_len;
		char *out_msg_val;
	} out_msg;
};
typedef struct list_output list_output;

struct delete_input {
	char user_name[10];
	char file_name[10];
};
typedef struct delete_input delete_input;

struct delete_output {
	struct {
		u_int out_msg_len;
		char *out_msg_val;
	} out_msg;
};
typedef struct delete_output delete_output;

struct close_input {
	char user_name[10];
	int fd;
};
typedef struct close_input close_input;

struct close_output {
	struct {
		u_int out_msg_len;
		char *out_msg_val;
	} out_msg;
};
typedef struct close_output close_output;

#define SSNFSPROG 0x31110023
#define SSNFSVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define open_file 1
extern  open_output * open_file_1(open_input *, CLIENT *);
extern  open_output * open_file_1_svc(open_input *, struct svc_req *);
#define read_file 2
extern  read_output * read_file_1(read_input *, CLIENT *);
extern  read_output * read_file_1_svc(read_input *, struct svc_req *);
#define write_file 3
extern  write_output * write_file_1(write_input *, CLIENT *);
extern  write_output * write_file_1_svc(write_input *, struct svc_req *);
#define list_files 4
extern  list_output * list_files_1(list_input *, CLIENT *);
extern  list_output * list_files_1_svc(list_input *, struct svc_req *);
#define delete_file 5
extern  delete_output * delete_file_1(delete_input *, CLIENT *);
extern  delete_output * delete_file_1_svc(delete_input *, struct svc_req *);
#define close_file 6
extern  close_output * close_file_1(close_input *, CLIENT *);
extern  close_output * close_file_1_svc(close_input *, struct svc_req *);
extern int ssnfsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define open_file 1
extern  open_output * open_file_1();
extern  open_output * open_file_1_svc();
#define read_file 2
extern  read_output * read_file_1();
extern  read_output * read_file_1_svc();
#define write_file 3
extern  write_output * write_file_1();
extern  write_output * write_file_1_svc();
#define list_files 4
extern  list_output * list_files_1();
extern  list_output * list_files_1_svc();
#define delete_file 5
extern  delete_output * delete_file_1();
extern  delete_output * delete_file_1_svc();
#define close_file 6
extern  close_output * close_file_1();
extern  close_output * close_file_1_svc();
extern int ssnfsprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_open_input (XDR *, open_input*);
extern  bool_t xdr_open_output (XDR *, open_output*);
extern  bool_t xdr_read_input (XDR *, read_input*);
extern  bool_t xdr_read_output (XDR *, read_output*);
extern  bool_t xdr_write_input (XDR *, write_input*);
extern  bool_t xdr_write_output (XDR *, write_output*);
extern  bool_t xdr_list_input (XDR *, list_input*);
extern  bool_t xdr_list_output (XDR *, list_output*);
extern  bool_t xdr_delete_input (XDR *, delete_input*);
extern  bool_t xdr_delete_output (XDR *, delete_output*);
extern  bool_t xdr_close_input (XDR *, close_input*);
extern  bool_t xdr_close_output (XDR *, close_output*);

#else /* K&R C */
extern bool_t xdr_open_input ();
extern bool_t xdr_open_output ();
extern bool_t xdr_read_input ();
extern bool_t xdr_read_output ();
extern bool_t xdr_write_input ();
extern bool_t xdr_write_output ();
extern bool_t xdr_list_input ();
extern bool_t xdr_list_output ();
extern bool_t xdr_delete_input ();
extern bool_t xdr_delete_output ();
extern bool_t xdr_close_input ();
extern bool_t xdr_close_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SSNFS_H_RPCGEN */
